### PR TITLE
kbs: allow resource uri to have `.` in safe ways

### LINKED ISSUE #593: Retrieving a resource with name with extension throws error
### Describe the bug

Retrieving a resource with name having the pattern <name>.<ext> fails with the following error
"[2024-11-24T12:59:21Z ERROR kbs::error] PluginInternalError { source: illegal ResourceDesc format. }"

### How to reproduce

Create a secret `key.pub` or `key.txt` under `/opt/confidential-containers/kbs/repository/default/secret/` and retrieve it using CDH.

```
curl http://127.0.0.1:8006/cdh/resource/default/secret/key.txt

rpc status: Status { code: INTERNAL, message: "[CDH] [ERROR]: Get Resource failed", details: [], special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
```

Following error is thrown on the Trustee KBS side
```
"[2024-11-24T12:59:21Z ERROR kbs::error] PluginInternalError { source: illegal ResourceDesc format. }"
```

### CoCo version information

main

### What TEE are you seeing the problem on

Snp

### Failing command and relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Xynnn007**
We deprecated `.` in resource uri to avoid security issues like accessing the upper directory with `..` path. However, in some cases `.` is safe like `example.txt`. This patch allows a string not starting with `.` to appear in a resource URI.

Fixes #593

cc @bpradipt

### CODE REVIEW

File: kbs/src/plugins/implementations/resource/backend.rs [hunk 1]
```diff
@@ -38,7 +38,7 @@ impl TryFrom<&str> for ResourceDesc {
     fn try_from(value: &str) -> Result<Self> {
         let regex = CELL.get_or_init(|| {
             Regex::new(
-                r"^((?<repo>[a-zA-Z0-9_\-]+)/)?(?<type>[a-zA-Z0-9_\-]+)/(?<tag>[a-zA-Z0-9_\-]+)$",
+                r"^((?<repo>[a-zA-Z0-9_\-]+[a-zA-Z0-9_\-\.]*)/)?(?<type>[a-zA-Z0-9_\-]+[a-zA-Z0-9_\-\.]*)/(?<tag>[a-zA-Z0-9_\-]+[a-zA-Z0-9_\-\.]*)$",
```
Comment (bpradipt) [inline kbs/src/plugins/implementations/resource/backend.rs:41]: Putting the regex in online validator (https://regex101.com/) complains about unescaped `/`. 
Following pattern with escaping the `/` worked
```
"^((?<repo>[a-zA-Z0-9_\-]+[a-zA-Z0-9_\-\.]*)\/)?(?<type>[a-zA-Z0-9_\-]+[a-zA-Z0-9_\-\.]*)\/(?<tag>[a-zA-Z0-9_\-]+[a-zA-Z0-9_\-\.]*)$"
```

Comment (Xynnn007) [reply kbs/src/plugins/implementations/resource/backend.rs:41]: Thanks. Let me fix this

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by fitzthum — APPROVED** [review]
LGTM
