### PR TITLE
Kbs/fix resource path policy

### LINKED ISSUE #1097: docs and testing is wrong for KBS resource policy `resource-path`
### Describe the bug

This issue is primarily about a mismatch in all our docs vs KBS (resource) policy evaluation for `resource-path`. With the move to the plugin model, the `resource-path` passed to `evaluate()` takes:

```rust
let endpoint = format!("{base_path}{additional_path}"); 
```

This means that with `path := split(data["resource-path"], "/")`, we get:

```
path[0] == "resource"
```

and the "three segment path format:`<TOP>/<MIDDLE>/<TAIL>`"  follows starting from `path[1]`.

The gap with testing is that while we have a lot of tests running `evaluate()` with `resource-path` set and policies written for it, they follow the old path structure which is not what API server users get.

Suggested fixes:
- update all our docs to `resource/<TOP>/<MIDDLE>/<TAIL>` model
- add e2e to test that structure
- update unit tests that also reflect this new `endpoint` structure
- (update the docs to highlight that plugins can use `path[0]` to identify themselves(?))
- (extra: cleanup `tcb-status` from .rego files since it's from Simple token)

### How to reproduce

Pick any policy that tests `path[0] == <TOP>`. This gives `PolicyDeny`.

### CoCo version information

trustee v0.15.0

### What TEE are you seeing the problem on

None

### Failing command and relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Xynnn007**
Fixes #1097 

Please see concrete commit messages

~~User interface change:~~
~~1. rename all kbs resource policy to kbs request policy~~
~~2. add a new `set-request-policy` subcommand for kbs-client, also for compability keep `set-resource-policy`. The two have same behavior~~

### CODE REVIEW

File: kbs/src/policy_engine/opa/mod.rs [hunk 1]
```diff
@@ -43,8 +43,8 @@ impl PolicyEngineInterface for Opa {
 
         // Add resource path as data
         let resource_path_object =
-            regorus::Value::from_json_str(&format!("{{\"resource-path\":\"{}\"}}", resource_path))
-                .map_err(|_| KbsPolicyEngineError::ResourcePathError)?;
+            regorus::Value::from_json_str(&format!("{{\"request_path\":\"{}\"}}", request_path))
+                .map_err(|_| KbsPolicyEngineError::RequestPathError)?;
```
Comment (mythi) [inline kbs/src/policy_engine/opa/mod.rs]: we could do this but another idea would be to split the path here to what it was:

```
      {{
            "resource-path": "..."
            "plugin-path": "<plugin>"
        }}
```

Comment (Xynnn007) [reply kbs/src/policy_engine/opa/mod.rs]: This would be a good plan, while `resource-path` is only for `resource` plugin. What about using
```json
{
  "plugin": "plugin",
  "parameter": "a/b/c",
  "quey": ["d=1", "e", "f=3"]
}
```
for 

`plugin/a/b/c?d=1&e&f=3`

File: kbs/docs/kbs.yaml [hunk 2]
```diff
@@ -284,14 +295,14 @@ components:
...
-    ResourcePolicy:
+    Policy:
       required:
         - policy
       properties:
         policy:
           type: string
           description: >-
-            Base64 encoded resource distribution policy.
+            Base64 encoded resource distribution policy. (original ResourcePolicy object)
```
Comment (pawelpros) [inline kbs/docs/kbs.yaml]:
```suggestion
           Base64-encoded policy for resource distribution, formerly referred to as ResourcePolicy.
```

File: kbs/config/kubernetes/ita/policy.rego [hunk 3]
```diff
@@ -1,42 +1,52 @@
-# Resource Policy
+# KBS Request Policy
```
Comment (pawelpros) [inline kbs/config/kubernetes/ita/policy.rego]:
```suggestion
# KBS Request Policy
```

File: kbs/src/policy_engine/opa/mod.rs (hunk 1 above)
Comment (pawelpros) [reply kbs/src/policy_engine/opa/mod.rs]: For me it's good idea (typo in "query")

Comment (mythi) [reply kbs/src/policy_engine/opa/mod.rs]: I was thinking `resource-path` for backwards compatibility and smoother transition to whatever the new keys would be.

Comment (fitzthum) [reply kbs/src/policy_engine/opa/mod.rs]: Yeah I think it's fine to keep it as resource path and even to keep referring to everything the KBS does as resources even if they're coming from plugins.

Comment (Xynnn007) [reply kbs/src/policy_engine/opa/mod.rs]: Yes, under the semantics of RESTful, practically everything can be called a resource. I'll revert it to a resource policy, while retaining the fine-grained parameters introduced by the PR in the policy engine.

File: kbs/src/policy_engine/opa/default_policy.rego [hunk 4]
```diff
@@ -1,41 +1,67 @@
...
+#    }
+#    ```
+#
+#    The original path string format is: <plugin-name>/.../<END>[?a=b&...&<QUERY>]
+#    Examples:
+#      - "resource/myrepo/License/key"
+#      - "<plugin-name>/para/meters?version=1.0.0"
+#
+#    For the "resource" plugin specifically:
+#      - subResourcePath format: /<repo>/<type>/<tag>
```
Comment (mythi) [inline kbs/src/policy_engine/opa/default_policy.rego]: As far as I can see, `subResourcePath` is available to *all* plugins but the structure is not defined. Should we say: 
```suggestion
#      - "<plugin-name>/<subResourcePath>?version=1.0.0"
#
#    For the "resource" plugin specifically:
#      - subResourcePath must have format: /<repo>/<type>/<tag>
```

File: kbs/src/policy_engine/opa/mod.rs (hunk 1 above)
Comment (fitzthum) [reply kbs/src/policy_engine/opa/mod.rs]: If we want to rename something we might consider renaming the resource plugin.

File: kbs/src/policy_engine/opa/default_policy.rego (hunk 4 above)
Comment (Xynnn007) [reply kbs/src/policy_engine/opa/default_policy.rego]: It's defined on line 36. but I get your point to have a regular representation here. As `<subResourcePath>` starts with `/`, so `<plugin-name><subResourcePath>` is right, but it's confusing. Do you have some ideas?

File: kbs/src/policy_engine/opa/mod.rs [hunk 5]
```diff
@@ -175,35 +169,141 @@ mod tests {
...
         1,
-        Err(KbsPolicyEngineError::ResourcePathError)
+        Ok(false)
     )]
     #[case(
         "test/data/policy_invalid_2.rego",
-        "my_repo/Alice/key",
+        json!({
+            "plugin": "resource",
+            "subResourcePath": "/my_repo/Alice/key",
```
Comment (mythi) [inline kbs/src/policy_engine/opa/mod.rs]: some leftover here?

File: kbs/src/policy_engine/opa/default_policy.rego [hunk 6]
```diff
@@ -1,41 +1,83 @@
...
+#        "plugin": "plugin1",
+#        "resource-path": "/para/meters",
+#        "query": {
+#           "version": "1.0.0"
+#        }	
+#    }
+#    ```
+#
+#    For the "resource" plugin specifically:
+#      - resource-path format: /<repo>/<type>/<tag>
```
Comment (mythi) [inline kbs/src/policy_engine/opa/default_policy.rego]: The `/` prefix for `<repo>` makes Rego `split()` to give 4 elements?

File: kbs/src/policy_engine/opa/mod.rs (hunk 5 above)
Comment (mythi) [inline kbs/src/policy_engine/opa/mod.rs]: leftover?

Comment (Xynnn007) [reply kbs/src/policy_engine/opa/mod.rs]: Oh yes. Let me fix

Comment (Xynnn007) [reply kbs/src/policy_engine/opa/mod.rs]: Let me fix this.

File: kbs/src/policy_engine/opa/default_policy.rego (hunk 6 above)
Comment (Xynnn007) [reply kbs/src/policy_engine/opa/default_policy.rego]: Yes.

Comment (mythi) [reply kbs/src/policy_engine/opa/default_policy.rego]: OK, I guess we have to accept this change since the path is no longer for the KBS resources but generic to any plugin.

File: kbs/src/api_server.rs [hunk 7]
```diff
@@ -125,7 +130,7 @@ impl ApiServer {
                         (1024 * 1024 * http_config.payload_request_size) as usize,
                     ))
                     .service(
-                        web::resource([kbs_path!("{base_path}{additional_path:.*}")])
+                        web::resource([kbs_path!("{plugin}{resource_path:.*}")])
```
Comment (fitzthum) [inline kbs/src/api_server.rs]: I always find this macro a little confusing. Can you add a comment to describe what is happening (like how is it splitting the path) or maybe it would be clearer to split the path later using more standard rust?

File: kbs/src/policy_engine/mod.rs [hunk 8]
```diff
@@ -24,13 +24,13 @@ pub const DEFAULT_POLICY_PATH: &str = "/opt/confidential-containers/kbs/policy.r
 pub(crate) trait PolicyEngineInterface: Send + Sync {
     /// Determine whether there is access to a specific path based on the input claims.
     /// Input parameters:
-    /// request_path: Required to be a string in segments path format:<FIRST>/.../<END>, for example: "my'repo/License/key".
-    /// input_claims: Parsed claims from Attestation Token.
+    /// data: data to be evaluated for regorus (rego) engine, in JSON format.
```
Comment (fitzthum) [inline kbs/src/policy_engine/mod.rs:27]: I find `data` to be a little vague, but I guess this is all going to change with the upcoming unified policy engine stuff.

File: kbs/src/policy_engine/opa/default_policy.rego [hunk 9]
```diff
@@ -1,41 +1,83 @@
...
+# below for specific conditions.
 
 package policy
 
 default allow = false
 
+plugin = data.plugin
+
 allow if {
+	plugin == "resource"
```
Comment (fitzthum) [inline kbs/src/policy_engine/opa/default_policy.rego:84]: I'm not sure this is really necessary, but I am fine with it.

File: kbs/test/data/policy_1.rego [hunk 10]
```diff
@@ -2,9 +2,10 @@ package policy
 
 default allow = false
 
-path := split(data["resource-path"], "/")
+subpaths := split(data["resource-path"], "/")
```
Comment (fitzthum) [inline kbs/test/data/policy_1.rego]: A lot of policies end up splitting the resource path into different fields. Maybe we should do this automatically and have the data contain a list of individual fields rather than one string? Maybe that is more cumbersome to work with in some circumstances idk

File: kbs/src/api_server.rs (hunk 7 above)
Comment (Xynnn007) [reply kbs/src/api_server.rs]: Yes it's somehow a magic. Let me replace with rust logic

File: kbs/src/policy_engine/mod.rs (hunk 8 above)
Comment (Xynnn007) [reply kbs/src/policy_engine/mod.rs:27]: Yes. Data is an OPA conception, alongside with input.

File: kbs/src/policy_engine/opa/default_policy.rego (hunk 9 above)
Comment (Xynnn007) [reply kbs/src/policy_engine/opa/default_policy.rego:84]: This statement is to ensure semantic consistency with previous behavior - by explicitly show it.

File: kbs/test/data/policy_1.rego (hunk 10 above)
Comment (Xynnn007) [reply kbs/test/data/policy_1.rego]: This would introduce some more changes. Let me add a separate commit and see if it is acceptable.

File: kbs/src/policy_engine/opa/default_policy.rego (hunk 9 above)
Comment (mythi) [reply kbs/src/policy_engine/opa/default_policy.rego:84]: how about we explain this to users in the commented section too (`For the "resource" plugin specifically`) so that it's easier to see why it's in here?

File: kbs/test/data/policy_1.rego (hunk 10 above)
Comment (Xynnn007) [reply kbs/test/data/policy_1.rego]: https://github.com/confidential-containers/trustee/pull/1098/commits/c6d3e747d56ffaab1e31a4b5fb29ee5964275ae3

File: kbs/src/policy_engine/opa/default_policy.rego (hunk 9 above)
Comment (Xynnn007) [reply kbs/src/policy_engine/opa/default_policy.rego:84]: Added to `Policy Rules`
